services:
  - type: web
    name: unipath
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: TIKTOK_CLIENT_KEY
        sync: false
      - key: TIKTOK_CLIENT_SECRET
        sync: false
      - key: ADMIN_SECRET
        sync: false
